categories:
  - 'music'
  - 'sport'
  - 'fitness'
  - 'entertainment'
  - 'comedy'
  - 'autos'
  - 'technologies'
  - 'fashion'
  - 'lifestyle'
  - 'nature'
  - 'relationships'
  - 'society'
  - 'informative'
  - 'food'
  - 'cook'
  - 'beauty'
